[package]
name = "electoral_bond"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
quick-xml = "0.31.0"
serde = {verison = "1.0.197", features=["derive"]}
serde_json = "1.0.114"
